#!/bin/bash

## git delete local branch with -D
branches=$(
  git --no-pager branch \
    --format="%(if)%(HEAD)%(then)%(else)%(if:equals=HEAD)%(refname:strip=3)%(then)%(else)%1B[0;34;1mbranch%09%1B[m%(refname:short)%(end)%(end)" \
  | sed '/^$/d') || exit
target=$(
  (echo "$branches";) |
  fzf --no-hscroll --no-multi -n 2 \
      --ansi --preview="git --no-pager log -150 --pretty=format:%s '..{2}'") || exit
git branch -D $(awk '{print $2}' <<<"$target" )
